server {
    listen 80;
    server_name mytripost.com www.mytripost.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name mytripost.com www.mytripost.com;

    ssl_certificate /etc/letsencrypt/live/mytripost.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mytripost.com/privkey.pem;
    
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    root /var/www/html/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass laravel:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTPS on;
        fastcgi_param SERVER_PORT 443;
    }

    location ~ /\.ht {
        deny all;
    }
    
    location ~ /.well-known/acme-challenge {
        allow all;
        root /var/www/html/public;
    }
}
